---
title: "Untitled"
output: html_document
date: '2022-07-01'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(jsonlite)
library(ggthemes)
library(tidycensus)
```

Poorer areas don't have access to grocery stores and have to walk miles to feed themselves.

```{r}
json_url <- "https://services1.arcgis.com/RLQu0rK7h4kbsBq5/arcgis/rest/services/Store_Locations/FeatureServer/0/query?where=State%20%3D%20'MA'%20AND%20County%20%3D%20'MIDDLESEX'&outFields=County,State,Store_Name,Longitude,Latitude&outSR=4326&f=json"

county_stores <- fromJSON(json_url)
county_stores <- county_stores$features$attributes

county_map <- get_acs(geography = "tract",
        variables = "B06012_002",
        year = 2018,
        state = "Massachusetts",
        county = "Middlesex County",
        geometry = TRUE,
        summary_var = "B02001_001")
```

```{r}
county_map |> 
  mutate(Percent = estimate * 100/ summary_est) |> 
  ggplot(aes(fill = Percent, color = Percent)) +
    geom_sf() +
    scale_fill_viridis_c(direction = -1) +
    scale_color_viridis_c(direction = -1) +
      geom_point(data = county_stores, 
               inherit.aes = FALSE,
               size = 0.5,
               aes(x = Longitude,
                   y = Latitude)) +
  labs(title = "Grocery Stores and Income in Middlesex County, MA", 
       subtitle = "Middlesex has a small food desert in the west",
       caption = "AP Retailer Locator, U.S. Department of Agriculture Food and Nutrition Service") + 
  theme_void()

```

